Fix a panic while compiling in a docker armv7 container
Hopefully fixes that error:

```
error: failed to run custom build command for `libmodbus-sys v0.4.2 (file:///root/libmodbus-rs/libmodbus-sys)`
process didn't exit successfully: `/root/libmodbus-rs/target/debug/build/libmodbus-sys-4ee06b86fff6f3f3/build-script-build` (exit code: 101)
--- stderr
You need to run this command from the toplevel of the working tree.
thread 'main' panicked at '', libmodbus-sys/build.rs:128:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: build_script_build::run_command
             at libmodbus-sys/build.rs:128
   7: build_script_build::main
             at libmodbus-sys/build.rs:50
   8: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
   9: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  10: main
  11: __libc_start_main
  12: <unknown>
```